baseURL = "http://ev-jiang.vercel.app"
title = "JIANG"
theme = "hugo-coder"
languageCode = "zh"
defaultContentLanguage = "zh"
paginate = 20
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
info = ["`Android Developer`", "`Frontend Developer`", "`Nonsenseist`"]
author = "JIANG"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "我坐在九千个日落里"
keywords = "blog,developer,personal"
enableTwemoji = true
# avatarURL = "https://avatars.githubusercontent.com/u/30593839"
avatarURL = "images/avatar.png"
# gravatar = "john.doe@example.com"
dateFormat = "2006,January 2"
since = 2020
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 7
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []


[params.giscus] # https://giscus.app
repo = "kunieone/blog-giscus"
repoID = "R_kgDOJzvukg"
category = "Announcements"
categoryID = "DIC_kwDOJzvuks4CXc2u"
mapping = "pathname"
# term = ""
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "light_protanopia"
lang = "zh-CN"
# loading = ""

[taxonomies]
categories = "categories"
tags = "tags"
# series = "series"
# nonsence = "nonsence"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/kunieone/"


[[params.social]]
name = "DEVTO"
icon = "fa fa-2x fa-dev-to"
weight = 1
url = "https://dev.to/starevan/"


[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@zstarcc"

[languages.zh]
languageName = ":cn:"


[[menu.main]]
name = "分类"
weight = 0
url = "categories/"

[[menu.main]]
name = "文章"
weight = 1
url = "posts/"

[[menu.main]]
name = "杂言"
weight = 2
url = "nonsence/"


[[menu.main]]
name = "标签"
weight = 3
url = "tags/"

[[menu.main]]
name = "关于"
weight = 4
url = "about/"
